@startuml
!pragma teoz true


title SDL decide that MOBILE is an access point
participant HMI
participant SDL
participant APP

note over HMI, APP: in ini file : NetworkHost = MOBILE \n\
App allowed to use feature by policies


SDL -> HMI : <b>UI.GetCapabilities() request
HMI -> SDL : <b>UI.GetCapabilities(NetworkingCapabilities) response : \n\
\t autoJoinWiFiSupported : \t true \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **MOBILE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

APP -> SDL : <b>RAI(NetworkCapabilities): \n\
\t autoJoinWiFiSupported : \t true \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **MOBILE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ"

SDL -> HMI : <b>OnAppRegistered 
SDL -> APP : <b>RAI response 

SDL -> SDL : Based on ini file, RAI and HMI NetworkCapabilities\n\
SDL decide that **Mobile should be AP** 


SDL -> HMI:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **MOBILE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> APP:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **MOBILE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ"  

APP -> APP : Mobile creates \n\
WiFi Aceess Point


APP -> SDL: <b>JoinNetwork request\n\
\t ssid : \t DeviceWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 \n\
\t allowAccessPointToBeShared : \t **false** \n\
\t accesssPointSupportsInternetAccess : \t true

SDL -> HMI: <b>JoinNetwork request\n\
\t ssid : \t DeviceWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 \n\
\t allowAccessPointToBeShared : \t **false** \n\
\t accesssPointSupportsInternetAccess : \t true

HMI -> HMI : Establish \n\
WiFiConnection

HMI -> SDL : <b>JoinNetwork response
SDL -> APP : <b>JoinNetwork response


HMI -> SDL:  <b>OnSystemCapabilityUpdate(NetworkConfiguration): \n\
\t autoJoinWiFiSupported : \t **false** \n\
\t canHostWiFiNetwork : \t **false**  \n\

@enduml
