@startuml
!pragma teoz true

title Negative cases 

participant HMI
participant SDL
box "Device1"
participant APP1
participant APP2
end box
box "Device2"
participant APP3
end box

note over HMI, APP2: in ini file : NetworkHost = VEHICLE \n\
Apps allowed to use feature by policies

SDL -> HMI : <b>UI.GetCapabilities() request
HMI -> SDL : <b>UI.GetCapabilities(NetworkingCapabilities) response : \n\
\t autoJoinWiFiSupported : \t **false** \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

APP1 -> SDL : <b>RAI_1(NetworkingCapabilities): \n\
\t autoJoinWiFiSupported : \t **false** \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **MOBILE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> HMI : <b>OnAppRegistered(App1) 
SDL -> APP1 : <b>RAI(App1) response 


SDL -> SDL : Based on ini file, RAI_1(App1) and HMI NetworkCapabilities\n\
**Feature is not initialized ** 

note over SDL: **Feature cannot be initialized**  \n\
HMI:  autoJoinWiFiSupported = **false**  \n\
API: autoJoinWiFiSupported = **false** \n\
SDL does not send OnNetworkConfiguration to HMI and APP

alt SDL rejects JoinNetwork request from App \n\
if the feature is not initialized

APP1 -> SDL: <b>JoinNetwork request\n\
\t ssid : \t DeviceWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 

SDL -> APP1 : <b>JoinNetwork response: resultCode = "REJECTED"

end 

APP2 -> SDL : <b>RAI_2(NetworkingCapabilities): \n\
\t autoJoinWiFiSupported : \t true \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> HMI : <b>OnAppRegistered(App2) 
SDL -> APP2 : <b>RAI_2(App2) response 

SDL -> SDL : Based on ini file, RAI(App2) and latest HMI NetworkCapabilities\n\
SDL decide that **VEHICLE should be AP** 

SDL -> HMI:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> APP1:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

alt SDL rejects JoinNetwork request from App \n\
if the networkhost: VEHICLE 


APP2 -> SDL: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 

SDL -> APP2 : <b>JoinNetwork response: resultCode = "REJECTED"

end

HMI -> HMI : HMI creates WiFi Aceess Point

alt HMI should send OnSystemCapabilityUpdate even \n\
if the capabilities are not changed 
HMI -> SDL : <b> OnSystemCapabilityUpdate(NetworkingCapabilities) \n\
\t autoJoinWiFiSupported : \t true \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 
end

note over HMI: HMI shows pop-up \n\
user consent 

HMI -> SDL: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 

SDL -> APP2: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

note over APP2: HMI shows pop-up \n\
user consent 

APP2 -> APP2 : WiFiConnection \n\
is not established and \n\
app does not send response\n\
due to some error


APP3 -> SDL : <b>RAI_3(NetworkingCapabilities): \n\
\t autoJoinWiFiSupported : \t true \n\
\t canHostWiFiNetwork : \t true \n\
\t preferredNetworkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> HMI : <b>OnAppRegistered(App3) 
SDL -> APP3 : <b>RAI_3(App3) response 


SDL -> SDL : Based on ini file, RAI(App3) and latest HMI NetworkCapabilities\n\
SDL decide that **VEHICLE should be AP** 



SDL -> HMI:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

SDL -> APP3:  <b>OnNetworkConfiguration(NetworkConfiguration): \n\
\t networkHost : \t **VEHICLE** \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 


HMI -> SDL: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 

SDL -> APP2: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

APP2 -> APP2 : WiFiConnection \n\
is not established

SDL -> APP3: <b>JoinNetwork request\n\
\t ssid : \t InCarWiFiAP \n\
\t password : \t 12345678 \n\
\t securityType : \t WIFI_SECURITY_WPA2 \n\
\t wifiFrequencyBandsSupported : \t "FREQUENCY_BAND_2_4_GHZ" 

APP3 -> APP3 : WiFiConnection \n\
is not established

APP3 -> SDL: <b>JoinNetwork response: resultCode = "REJECTED"
SDL -> HMI: <b>JoinNetwork response: resultCode = "REJECTED"

@enduml